In [1]:
!pip install wikipedia-api


In [2]:
import numpy as np
import tensorflow as tf
import wikipediaapi
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical


2024-05-12 07:08:00.207309: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-05-12 07:08:00.207431: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-05-12 07:08:00.340859: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [3]:
# Fetch Wikipedia article
def fetch_wikipedia_text(topic):
      wiki_wiki = wikipediaapi.Wikipedia(
      language='en',
      extract_format=wikipediaapi.ExtractFormat.WIKI,
      user_agent='my-application/1.0')
      page = wiki_wiki.page(topic)
      return page.text

# Preprocess text
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove special characters
    text = ''.join(c for c in text if c.isalnum() or c in [' ', '\n'])
    return text

In [4]:
topic = "Artificial intelligence"
wikipedia_text = fetch_wikipedia_text(topic)
preprocessed_text = preprocess_text(wikipedia_text)
print(preprocessed_text)


artificial intelligence ai in its broadest sense is intelligence exhibited by machines particularly computer systems it is a field of research in computer science that develops and studies methods and software that enable machines to perceive their environment and uses learning and intelligence to take actions that maximize their chances of achieving defined goals such machines may be called ais
ai technology is widely used throughout industry government and science some highprofile applications include advanced web search engines eg google search recommendation systems used by youtube amazon and netflix interacting via human speech eg google assistant siri and alexa autonomous vehicles eg waymo generative and creative tools eg chatgpt and ai art and superhuman play and analysis in strategy games eg chess and go however many ai applications are not perceived as ai a lot of cutting edge ai has filtered into general applications often without being called ai because once something become

In [5]:
# Create character-to-integer mapping
chars = sorted(list(set(preprocessed_text)))
char_to_int = {c: i for i, c in enumerate(chars)}
int_to_char = {i: c for i, c in enumerate(chars)}

# Convert characters to numerical representations
encoded_text = [char_to_int[c] for c in preprocessed_text]

# Define sequence length
seq_length = 100
# Generate sequences
sequences = []
for i in range(0, len(encoded_text) - seq_length, 1):
    sequences.append(encoded_text[i:i + seq_length + 1])

# Convert sequences to numpy arrays
X = np.array([seq[:-1] for seq in sequences])
y = np.array([seq[-1] for seq in sequences])
print(X )
print("------------------------------------------------------------------------------------------")
print(y)


[[12 29 31 ... 23 36  1]
 [29 31 20 ... 36  1 14]
 [31 20 17 ...  1 14 26]
 ...
 [16 22 30 ... 15 20 14]
 [22 30 12 ... 20 14 20]
 [30 12 25 ... 14 20 25]]
------------------------------------------------------------------------------------------
[14 26 24 ... 20 25 16]


In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dropout, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dropout, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dropout, Dense
# Build the model
vocab_size = 10000  # Number of unique characters or vocabulary size
seq_length = 100  # Length of input sequences


model = Sequential([
    Embedding(vocab_size, 64, input_length=seq_length), 
    SimpleRNN(128, return_sequences=True), 
    Dropout(0.2),  
    SimpleRNN(64),  
    Dropout(0.2),  
    Dense(vocab_size, activation='softmax')  
])


# Compile the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam')

# Train the model
model.fit(X, y, batch_size=128, epochs=50)


/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Epoch 1/50
  7/553 ━━━━━━━━━━━━━━━━━━━━ 10s 20ms/step - loss: 9.1798 

I0000 00:00:1715497700.420247     113 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


553/553 ━━━━━━━━━━━━━━━━━━━━ 21s 25ms/step - loss: 4.2605
Epoch 2/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9413
Epoch 3/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9441
Epoch 4/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9340
Epoch 5/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9314
Epoch 6/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9333
Epoch 7/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9361
Epoch 8/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9322
Epoch 9/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 4.4415
Epoch 10/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.9380
Epoch 11/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 19ms/step - loss: 2.8502
Epoch 12/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.7753
Epoch 13/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.7100
Epoch 14/50
553/553 ━━━━━━━━━━━━━━━━━━━━ 10s 18ms/step - loss: 2.6430
Epoch 15/50
553/553 ━━━━━━━━━━━━━━━━━━━━

In [7]:
def generate_text_base_char(model, seed_text, num_chars=100, seq_length=100):
    # Preprocess the seed text
    seed_text = preprocess_text(seed_text)
    generated_text = seed_text

    for _ in range(num_chars):
        # Convert seed text to numerical representation
        encoded_seed = [char_to_int.get(char, 0) for char in seed_text]  # Use `get` with a default value if char not found

        # Padding if necessary
        if len(encoded_seed) < seq_length:
            padding = [0] * (seq_length - len(encoded_seed))  # Assuming '0' is used for padding
            encoded_seed = padding + encoded_seed

        encoded_seed = np.array([encoded_seed[-seq_length:]])  # Ensure input is exactly `seq_length` long

        # Predict the next character
        predicted_probs = model.predict(encoded_seed)[0]
        predicted_index = np.random.choice(len(predicted_probs), p=predicted_probs)
        predicted_char = int_to_char[predicted_index]

        # Add predicted character to the generated text
        generated_text += predicted_char

        # Update seed text for next prediction
        seed_text += predicted_char
        seed_text = seed_text[1:]  # Sliding window

    return generated_text

seed_text = "Artificial intelligence is"
generated_text = generate_text_base_char(model, seed_text)
print(generated_text)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 609ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
1/1 ━━━━━━━

In [8]:
text = preprocessed_text
# Prepare the tokenizer and encode the words
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
encoded = tokenizer.texts_to_sequences([text])[0]
vocab_size = len(tokenizer.word_index) + 1

# Generate sequences
seq_length = 100
sequences = []
for i in range(seq_length, len(encoded)):
    seq = encoded[i-seq_length:i+1]
    sequences.append(seq)

sequences = np.array(sequences)
X, y = sequences[:,:-1], sequences[:,-1]
y = to_categorical(y, num_classes=vocab_size)






In [9]:
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
# Define the RNN model
model = Sequential([
    Embedding(vocab_size, 64, input_length=seq_length),
    SimpleRNN(128, return_sequences=True),
    Dropout(0.3),
    SimpleRNN(64),
    Dropout(0.3),
    Dense(vocab_size, activation='softmax')
])

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X, y, batch_size=128, epochs=500)

Epoch 1/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 13s 69ms/step - accuracy: 0.0210 - loss: 7.5251
Epoch 2/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.0438 - loss: 6.6249
Epoch 3/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0459 - loss: 6.6809
Epoch 4/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.0416 - loss: 6.6505
Epoch 5/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0403 - loss: 6.6825
Epoch 6/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0487 - loss: 6.5588
Epoch 7/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0526 - loss: 6.4301
Epoch 8/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0589 - loss: 6.2885
Epoch 9/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0530 - loss: 6.1755
Epoch 10/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0621 - loss: 6.0899
Epoch 11/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.0653 - loss: 5.9406
Epoch 12/500
86/86 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/ste

In [10]:
# Generate text function
def generate_text_base_word(model, tokenizer, seed_text, num_words):
    result = []
    in_text = seed_text
    for _ in range(num_words):
        encoded = tokenizer.texts_to_sequences([in_text])[0]
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        yhat = model.predict(encoded, verbose=0)
        yhat = np.argmax(yhat, axis=1)
        out_word = ''
        for word, index in tokenizer.word_index.items():
            if index == yhat:
                out_word = word
                break
        in_text += ' ' + out_word
        result.append(out_word)
    return ' '.join(result)

# Example usage
seed_text = "Artificial Intelligence"
generated_text = generate_text_base_word(model, tokenizer, seed_text, 100)
print(seed_text,generated_text)

Artificial Intelligence there is not very important for not a 21st between perceives and quality of knowledge is knowledge the same between scale it can then designed research that would ai no deductions century by iteration laws of the technology state vs a machines to help reoffend and 2017 several researchers showed that if used with thousands of toxic molecules in a matter of hours reliance on industry giants training ai systems requires an enormous amount of computing power usually only big tech companies have the financial resources to make such investments smaller startups such as cohere and openai end up buying


In [14]:
print(generated_text)

there is not very important for not a 21st between perceives and quality of knowledge is knowledge the same between scale it can then designed research that would ai no deductions century by iteration laws of the technology state vs a machines to help reoffend and 2017 several researchers showed that if used with thousands of toxic molecules in a matter of hours reliance on industry giants training ai systems requires an enormous amount of computing power usually only big tech companies have the financial resources to make such investments smaller startups such as cohere and openai end up buying
